Add dbs to exclude (+ fix prettier)
Tecnativa/docker-duplicity pull request #41
Opened 2020-11-16 13:50 UTC by joao-p-marques

Adds `DBS_TO_EXCLUDE` environment variable to filter `pg_dump` target dbs. 
Allows passing a regex to filter DBs.

Also updated prettier/prettier to prettier/pre-commit (#prettiermageddon)

@Tecnativa
TT26621

2020-11-17 09:20 UTC, Yajo requested changes

2020-11-17 09:20 UTC, Yajo commented on Dockerfile
> +ENV JOB_200_WHAT psql -0Atd postgres -c \"SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != \'postgres\'\" | grep --null-data --invert-match -E $DBS_TO_EXCLUDE | xargs -0tI DB pg
Does this work? If it does, it's better usually because under bash, a variable without double-quotes can do damage if it contains shell instructions, or just spaces.

```suggestion
ENV JOB_200_WHAT psql -0Atd postgres -c \"SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != \'postgres\'\" | grep --null-data --invert-match -E \"$DBS_TO_EXCLUDE\" | xargs -0tI DB pg_dump --dbname DB --no-owner --no-privileges --file \"\$SRC/DB.sql\"
```

2020-11-17 09:20 UTC, Yajo commented on README.md
> +DBS_TO_EXCLUDE="DB1|DB2"
Be more precise:

```suggestion
DBS_TO_EXCLUDE="^(DB1|DB2)$"
```

2020-11-17 09:20 UTC, Yajo commented on .pre-commit-config.yaml
> +    rev: v2.0.2
Maybe it's a good moment to bump the version?

2020-11-17 09:20 UTC, Yajo commented on Dockerfile
> +    DBS_TO_EXCLUDE='$^'
Sort these alphabetically please.

2020-11-23 11:00 UTC, joao-p-marques commented on .pre-commit-config.yaml
> +    rev: v2.0.2
Yes, I bumped to v2.2.0. Is that too much?

2020-11-23 11:00 UTC, joao-p-marques commented on .pre-commit-config.yaml
> +    rev: v2.0.2
Oh, and also moved to `pre-commit/mirrors-prettier` :smile:

2020-11-23 11:09 UTC, joao-p-marques commented
Changes made @Yajo. Thank you.
Also applied some changes needed for the CI to work, after the deprecation of `set-env`.

2020-11-23 13:26 UTC, Yajo requested changes

2020-11-23 13:26 UTC, Yajo commented on README.md
> +  - [`DBS_TO_EXCLUDE`](#dbs_to_exclude)
Please sort alphabetically.

2020-11-23 15:17 UTC, joao-p-marques commented on README.md
> +  - [`DBS_TO_EXCLUDE`](#dbs_to_exclude)
Done, ty!

2020-11-26 08:15 UTC, Yajo approved these changes

2020-11-26 08:15 UTC, merged