Update Github CI and CD
Tecnativa/docker-duplicity pull request #48
Opened 2020-12-21 10:56 UTC by joao-p-marques

Use **Github Container Registry** instead of deprecated Github packages

Update to **build-push-action v2**

Start using **buildx**

This should contribute to fixing the latest build errors.

ping @Yajo

2020-12-21 11:32 UTC, Yajo requested changes
Looks good, just one remainder I think.

2020-12-21 11:32 UTC, Yajo commented on .github/workflows/cd.yaml
> +          tag-sha: true # add git short SHA as Docker tag
Interesting, but you're not using it later, right?

2020-12-22 07:10 UTC, joao-p-marques commented on .github/workflows/cd.yaml
> +          tag-sha: true # add git short SHA as Docker tag
Yes, indeed. I forgot to add it bellow, should be done now.

This is the current equivalent to the `add_git_labels: true` in the old spec.

2020-12-22 08:19 UTC, Yajo commented on .github/workflows/cd.yaml
> +          tag-sha: true # add git short SHA as Docker tag
Awesome tool, I didn't know about it. Thanks 😊

2020-12-22 08:19 UTC, Yajo approved these changes

2020-12-22 08:19 UTC, merged

2020-12-22 08:21 UTC, joao-p-marques commented on .github/workflows/cd.yaml
> +          tag-sha: true # add git short SHA as Docker tag
Nice :+1: 
It is the suggested approach in the `build-push-action` since v2: https://github.com/docker/build-push-action#handle-tags-and-labels

2020-12-22 08:44 UTC, Yajo reviewed
https://github.com/Tecnativa/docker-duplicity/actions/runs/437598776 failed on master. Please check it. Also the comment below.

2020-12-22 08:44 UTC, Yajo commented on .github/workflows/cd.yaml
>            docker://docker.pkg.github.com/tecnativa/docker-duplicity/stable:docker
These comments lie. Please fix them.