Apply image template
Tecnativa/docker-duplicity pull request #54
Opened 2021-01-28 09:03 UTC by joao-p-marques

@Tecnativa
TT27819

Just need to rebase once #53 is merged.

2021-02-04 09:26 UTC, Yajo requested changes

2021-02-04 09:26 UTC, Yajo commented on README.md
> +`ghcr.io/tecnativa/docker-duplicity` on GHCR.
At this point, we might freeze the docker hub images and deprecate them. I think it will make all easier.

Besides, docs below for other flavors don't seem to really help find the proper images on ghcr. They point to docker hub images that don't exist.

2021-02-04 09:26 UTC, Yajo commented on .copier-answers.image-template.yml
> +  - linux/arm64/v8
Shouldn't there be armv7?

2021-02-04 09:26 UTC, Yajo commented on README.md
> +branch. Each individual git released version is also tagged (e.g. `:v0.1.0`)
AFAICS the images will be tagged like this:

```suggestion
branch. Each individual git released version is also tagged (e.g. `:0.1.0`)
```

2021-02-04 09:26 UTC, Yajo commented on README.md
> +   poetry add --optional MY_NEW_PACKAGE`
Don't you need this? 🤔 

```suggestion
   poetry add --extras duplicity --optional MY_NEW_PACKAGE
```

2021-02-04 09:26 UTC, Yajo commented on README.md
> +   poetry export -E duplicity -o requirements.txt`
```suggestion
   poetry export -E duplicity -o requirements.txt
```

2021-02-04 09:26 UTC, Yajo commented on README.md
> +1. Export the new poetry-resolved list of packages to the `requirements.txt` file:
We need a test that makes sure `requirements.txt` is up to date.

2021-02-04 09:37 UTC, joao-p-marques commented on README.md
> +`ghcr.io/tecnativa/docker-duplicity` on GHCR.
Mmm ok, I just think that it might leave many people hanging, as the majority should still be using the DockerHub image, right?
If we do that, we might need to post a warning note on Dockerhub or here.

I can also improve the documentation to better help finding the images on GHCR :+1:

2021-02-04 09:49 UTC, joao-p-marques commented on .copier-answers.image-template.yml
> +  - linux/arm64/v8
Well, I was trying to add architectures 1 by 1 to see which ones were breaking the builds after https://github.com/Tecnativa/docker-duplicity/commit/a8abdd6649c07ddeb282c6a7bac89d77ab1b2d49 and `arm/v7` was unable to build :man_shrugging: 

I also decided to leave `386`, `ppc64le` and `s390x` out as I don't think they will get much use and would slow the build significantly. Same with `arm/v6` as it seems to be quite old.
OTOH, `arm/v8` seems to be the most used arch now. It is the one present in the Raspberry Pi 4, for example.
I will try to add `linux/arm64` though, now that I think of it, as that might be more used in the community (it is the one on the new Macs, for example :sweat_smile:)

2021-02-04 09:49 UTC, joao-p-marques commented on README.md
> +branch. Each individual git released version is also tagged (e.g. `:v0.1.0`)
Yes, MB, thanks :+1:

2021-02-04 09:51 UTC, Yajo commented on README.md
> +`ghcr.io/tecnativa/docker-duplicity` on GHCR.
Yes, but the images names/tags is gonna change in a backwards incompatible manner, so I guess the best we can do is to freeze that image and put those warnings somewhere.

2021-02-04 10:04 UTC, joao-p-marques commented on README.md
> +   poetry add --optional MY_NEW_PACKAGE`
Well, the `poetry` CLI has caused me some doubts :sweat_smile: Seems like it is being updated right now and the docs are somewhat incomplete. 
When I run the command you suggested it will add an optional dependency named `MY_NEW_PACKAGE` but, instead of adding that to the extras section named `duplicity`, it will actually add the `duplicity` package as an extra of `MY_NEW_PACKAGE`:
```
poetry add --extras duplicity --optional pyyaml
```
```diff
 dropbox = {version = "^8.0.0", optional = true}
 python-keystoneclient = {version = "^3.10.0", optional = true}
 mediafire = {version = "^0.6.0", optional = true}
+PyYAML = {version = "^5.4.1", optional = true, extras = ["duplicity"]}
 
 [tool.poetry.dev-dependencies]
 pytest = "^6.2.1"
```
See https://github.com/python-poetry/poetry/pull/3156 and the related issues for reference. 

What I found is that the best way is to then add the new dependency to the `[tool.poetry.extras]` section bellow, as I explain further in the README.

2021-02-04 10:52 UTC, joao-p-marques commented on README.md
> +1. Export the new poetry-resolved list of packages to the `requirements.txt` file:
That already exists as a test step: https://github.com/Tecnativa/docker-duplicity/pull/54/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR59-R63
It would be better to port it to pytest, though :thinking: Hadn't thought of that :sweat_smile:

2021-02-04 12:17 UTC, joao-p-marques commented on README.md
> +`ghcr.io/tecnativa/docker-duplicity` on GHCR.
Ok, I just removed the whole DokerHub part and added some docs.

2021-02-05 07:48 UTC, joao-p-marques commented on .copier-answers.image-template.yml
> +  - linux/arm64/v8
Turns out the new Apple M1 is actually `linux/arm64/v8`, as the RPi: https://dockerquestions.com/2020/12/26/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8-in-the-manifest-list-entries/

Leaving just those 2 as adding `linux/arm64` also broke the builds.

2021-02-05 16:14 UTC, merged